version: '2'
services:
  grafana:
    build: grafana
    ports:
      - "127.0.0.1:9003:3000"
    restart: always
    volumes:
      - ./grafana-data/data:/var/lib/grafana
      - ./grafana-data/log:/var/log/grafana
      - ./grafana-data/config:/etc/grafana
    command: grafana-server  --config=/etc/grafana/grafana.ini -homepath /usr/share/grafana/ cfg:default.paths.provisioning=/etc/grafana/provisioning cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins
    depends_on:
      - prometheus

  prometheus:
    build: prometheus
    restart: always
    volumes:
      - ./prometheus-data/data:/prometheus
      - ./prometheus-data/config:/etc/prometheus


