grafana:
  build: .
  container_name: grafana
  ports:
    - "3000:3000"
  restart: always
  volumes:
    - ./grafana-data/data:/var/lib/grafana
    - ./grafana-data/log:/var/log/grafana
    - ./grafana-data/config:/etc/grafana
  command: "grafana-server -homepath /usr/share/grafana/ --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.provisioning=/etc/grafana/provisioning cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins"
